# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'ac2ed364d9b64d2846343ab477e5b4d948bee95a70b70e978f60ac22e24b5067'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack