# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if entity @s[tag=aj.weapons.animation.sword1.playing] run function animated_java:weapons/animations/sword1/zzz/on_tick
execute if entity @s[tag=aj.weapons.animation.sword2.playing] run function animated_java:weapons/animations/sword2/zzz/on_tick
execute if entity @s[tag=aj.weapons.animation.hoe1.playing] run function animated_java:weapons/animations/hoe1/zzz/on_tick
execute if entity @s[tag=aj.weapons.animation.hoe2.playing] run function animated_java:weapons/animations/hoe2/zzz/on_tick
execute if entity @s[tag=aj.weapons.animation.pickaxe1.playing] run function animated_java:weapons/animations/pickaxe1/zzz/on_tick
execute if entity @s[tag=aj.weapons.animation.axe1.playing] run function animated_java:weapons/animations/axe1/zzz/on_tick
execute if entity @s[tag=aj.weapons.animation.axe2.playing] run function animated_java:weapons/animations/axe2/zzz/on_tick
execute if entity @s[tag=aj.weapons.animation.shovel1.playing] run function animated_java:weapons/animations/shovel1/zzz/on_tick
execute if entity @s[tag=aj.weapons.animation.shovel2.playing] run function animated_java:weapons/animations/shovel2/zzz/on_tick
execute if entity @s[tag=aj.weapons.animation.jump1.playing] run function animated_java:weapons/animations/jump1/zzz/on_tick