# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify entity @s data.uuids append from storage animated_java:gu out
function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.data_data set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.left] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.right] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.cloth] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_cloth set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.upper] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_upper set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.item_display4] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_item_display4 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.head] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_head set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.item_display] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_item_display set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.item_display1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_item_display1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.item_display3] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_item_display3 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.right1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_right1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.item_display2] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.item_display_item_display2 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.left1] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_left1 set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.cape] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_cape set from storage animated_java:gu out
execute on vehicle on passengers if entity @s[tag=aj.second_officer.node.body] run function animated_java:global/gu/get_entity_uuid_string
data modify entity @s data.uuids append from storage animated_java:gu out
data modify entity @s data.uuids_by_name.bone_body set from storage animated_java:gu out