# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:second_officer/animations/pause_all
tag @s add aj.second_officer.animation.spin_slash.playing
scoreboard players set @s aj.spin_slash.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:second_officer/animations/spin_slash/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only