# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.second_officer.animation.idle.playing
tag @s remove aj.second_officer.animation.walk.playing
tag @s remove aj.second_officer.animation.jump.playing
tag @s remove aj.second_officer.animation.teleport_dark_hand.playing
tag @s remove aj.second_officer.animation.left_right.playing
tag @s remove aj.second_officer.animation.stab_far.playing
tag @s remove aj.second_officer.animation.spin_slash.playing
tag @s remove aj.second_officer.animation.up_down_long.playing