# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.carapacer.root] run return 0
execute on passengers if entity @s[tag=aj.carapacer.data] unless data entity @s {data:{rigHash: '69ca3a5196a34eed9912d956f3f443f601bfdbfbf3588d5d1eb51787f99207a4'}} on vehicle run function animated_java:carapacer/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1