# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.carapacer.root] run return 0
execute on passengers if entity @s[tag=aj.carapacer.data] unless data entity @s {data:{rigHash: 'e27abc865021f53f76bbea31ee191eab767f33463cd8964acef11d0584d3a838'}} on vehicle run function animated_java:carapacer/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1