# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.carapacer.root] run return 0
execute unless score @s aj.is_rig_loaded matches 1 run function #animated_java:global/root/on_load
execute if entity @s[tag=aj.carapacer.animation.transform__big_new.playing] run function animated_java:carapacer/animations/transform__big_new/zzz/on_tick
execute if entity @s[tag=aj.carapacer.animation.walk_small_new.playing] run function animated_java:carapacer/animations/walk_small_new/zzz/on_tick
execute if entity @s[tag=aj.carapacer.animation.walk_big_new.playing] run function animated_java:carapacer/animations/walk_big_new/zzz/on_tick
execute if entity @s[tag=aj.carapacer.animation.attack_new.playing] run function animated_java:carapacer/animations/attack_new/zzz/on_tick
execute if entity @s[tag=aj.carapacer.animation.idle_small_new.playing] run function animated_java:carapacer/animations/idle_small_new/zzz/on_tick
execute if entity @s[tag=aj.carapacer.animation.idle_big_new.playing] run function animated_java:carapacer/animations/idle_big_new/zzz/on_tick
execute at @s on passengers run rotate @s ~ ~