# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:weapons/animations/pause_all
tag @s add aj.weapons.animation.sword_far2.playing
scoreboard players set @s aj.sword_far2.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:weapons/animations/sword_far2/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only