# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:weapons/animations/pause_all
tag @s add aj.weapons.animation.jump1.playing
scoreboard players set @s aj.jump1.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:weapons/animations/jump1/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only