# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.05f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0175f,-0.025f,0f,0.0175f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0175f,0.075f,0f,0.0175f,-0.9998f,0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [-1f,0f,0f,0f,0f,0.9998f,-0.0175f,0f,0f,-0.0175f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left2) {transformation: [-1f,0f,0f,0f,0f,0.9998f,-0.0175f,0.1f,0f,-0.0175f,-0.9998f,-0.0017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_mouth2) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.8875f,0f,0f,-1f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_mouth) {transformation: [-1.0833f,0f,0f,0f,0f,1.0833f,0f,-0.8875f,0f,0f,-1.0833f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom_mouth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.7f,0f,0f,-1f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_main_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.7f,0f,0f,-1f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}