# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.0563f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.1125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_mouth2) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.8812f,0f,0f,-1f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_mouth) {transformation: [-1.0833f,0f,0f,0f,0f,1.0833f,0f,-0.8812f,0f,0f,-1.0833f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom_mouth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.6937f,0f,0f,-1f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_main_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.6937f,0f,0f,-1f,-0.75f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}