# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.jump.frame matches 71.. run scoreboard players set @s aj.jump.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.jump.frame
execute at @s run function animated_java:second_officer/animations/jump/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.jump.frame 1