# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_legs) {transformation: [-1f,0f,0f,0f,0f,0.9997f,0.0262f,1.25f,0f,0.0262f,-0.9997f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_backbling) {transformation: [-1f,0f,0f,0f,0f,1f,0.0065f,2.6903f,0f,0.0065f,-1f,-0.4281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1f,0f,0f,0f,0f,1f,0.0065f,2.125f,0f,0.0065f,-1f,0.0057f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0.0065f,1.25f,0f,0.0065f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.9824f,0.1865f,0f,-0.5f,0.148f,0.7796f,-0.6086f,2.375f,-0.1135f,-0.5979f,-0.7935f,0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-0.9998f,-0.0196f,0f,0.5f,-0.0196f,0.9998f,0f,2.375f,0f,0f,-1f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left2) {transformation: [-0.9999f,-0.0131f,0f,0.5f,-0.0131f,0.9999f,0f,2.5f,0f,0f,-1f,-0.2187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [-0.9999f,0.0131f,0f,-0.5f,0.0131f,0.9999f,0f,2.5f,0f,0f,-1f,-0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9999f,0.0131f,2.625f,0f,0.0131f,-0.9999f,0.1344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_spinny_part) {transformation: [-0.454f,-0.0065f,0.891f,-0.6714f,-0.003f,1f,0.0058f,2.25f,-0.891f,0f,-0.454f,0.7812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_staff) {transformation: [0f,-0.0113f,1.7291f,-0.6563f,0f,1.7291f,0.0113f,-0.0625f,-1.7292f,0f,0f,0.7812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{"camera":{"posx":-6.24767002099744e-17,"posy":2.682586047134121,"posz":0.5101609725634616,"roty":0,"rotx":0.7500000000000001}},"locators":{}}