# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_legs) {transformation: [-1f,0f,0f,0f,0f,0.9998f,0.0175f,1.25f,0f,0.0175f,-0.9998f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_backbling) {transformation: [-1f,0f,0f,0f,0f,1f,0.0044f,2.6894f,0f,0.0044f,-1f,-0.4312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1f,0f,0f,0f,0f,1f,0.0044f,2.125f,0f,0.0044f,-1f,0.0038f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0.0044f,1.25f,0f,0.0044f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.9833f,0.1823f,0f,-0.5f,0.1446f,0.7802f,-0.6086f,2.375f,-0.1109f,-0.5984f,-0.7935f,0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-0.9999f,-0.0131f,0f,0.5f,-0.0131f,0.9999f,0f,2.375f,0f,0f,-1f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left2) {transformation: [-1f,-0.0087f,0f,0.5f,-0.0087f,1f,0f,2.5f,0f,0f,-1f,-0.2187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [-1f,0.0087f,0f,-0.5f,0.0087f,1f,0f,2.5f,0f,0f,-1f,-0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0.0087f,2.625f,0f,0.0087f,-1f,0.1313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_spinny_part) {transformation: [-0.309f,-0.0044f,0.951f,-0.6663f,-0.0013f,1f,0.0041f,2.25f,-0.9511f,0f,-0.309f,0.7812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_staff) {transformation: [0f,-0.0075f,1.7292f,-0.6563f,0f,1.7292f,0.0075f,-0.0625f,-1.7292f,0f,0f,0.7812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{"camera":{"posx":-6.206278882546116e-17,"posy":2.6842251693796206,"posz":0.5067811296177126,"roty":0,"rotx":0.5}},"locators":{}}