# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_legs) {transformation: [-1f,0f,0f,0f,0f,1f,0.0087f,1.25f,0f,0.0087f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_backbling) {transformation: [-1f,0f,0f,0f,0f,1f,0.0022f,2.6885f,0f,0.0022f,-1f,-0.4344f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-1f,0f,0f,0f,0f,1f,0.0022f,2.125f,0f,0.0022f,-1f,0.0019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0.0022f,1.25f,0f,0.0022f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.984f,0.178f,0f,-0.5f,0.1412f,0.7807f,-0.6087f,2.375f,-0.1083f,-0.599f,-0.7934f,0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,-0.0065f,0f,0.5f,-0.0065f,1f,0f,2.375f,0f,0f,-1f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left2) {transformation: [-1f,-0.0044f,0f,0.5f,-0.0044f,1f,0f,2.5f,0f,0f,-1f,-0.2187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [-1f,0.0044f,0f,-0.5f,0.0044f,1f,0f,2.5f,0f,0f,-1f,-0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0.0044f,2.625f,0f,0.0044f,-1f,0.1281f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_spinny_part) {transformation: [-0.1564f,-0.0022f,0.9877f,-0.6613f,-0.0003f,1f,0.0022f,2.25f,-0.9877f,0f,-0.1564f,0.7812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_staff) {transformation: [0f,-0.0038f,1.7292f,-0.6563f,0f,1.7292f,0.0038f,-0.0625f,-1.7292f,0f,0f,0.7812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{"camera":{"posx":-6.164800187097595e-17,"posy":2.685863164063266,"posz":0.5033941371005721,"roty":0,"rotx":0.25}},"locators":{}}