# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.carapacer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'carapacer', 'function_path': 'animated_java:carapacer/animations/walk_big_new/next_frame'}
execute if score @s aj.walk_big_new.frame matches 16.. run scoreboard players set @s aj.walk_big_new.frame 1
data remove storage aj:temp args
execute store result storage aj:temp args.frame int 1 run scoreboard players get @s aj.walk_big_new.frame
execute at @s run function animated_java:carapacer/animations/walk_big_new/zzz/apply_frame with storage aj:temp args
scoreboard players add @s aj.walk_big_new.frame 1