# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:second_officer rig_hash set value 'ac2ed364d9b64d2846343ab477e5b4d948bee95a70b70e978f60ac22e24b5067'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.jump.frame dummy
scoreboard objectives add aj.teleport_dark_hand.frame dummy
scoreboard objectives add aj.left_right.frame dummy
scoreboard objectives add aj.stab_far.frame dummy
scoreboard objectives add aj.spin_slash.frame dummy
scoreboard objectives add aj.up_down_long.frame dummy