# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.idle.frame
scoreboard objectives remove aj.walk.frame
scoreboard objectives remove aj.jump.frame
scoreboard objectives remove aj.teleport_dark_hand.frame
scoreboard objectives remove aj.left_right.frame
scoreboard objectives remove aj.stab_far.frame
scoreboard objectives remove aj.spin_slash.frame
scoreboard objectives remove aj.up_down_long.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:second_officer)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'second_officer'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']