# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.carapacer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'carapacer', 'function_path': 'animated_java:carapacer/variants/damaged/apply'}
execute on passengers if entity @s[tag=aj.carapacer.bone.body] run function animated_java:carapacer/variants/damaged/zzz/apply_to_bone_body
execute on passengers if entity @s[tag=aj.carapacer.bone.left] run function animated_java:carapacer/variants/damaged/zzz/apply_to_bone_left
execute on passengers if entity @s[tag=aj.carapacer.bone.right] run function animated_java:carapacer/variants/damaged/zzz/apply_to_bone_right
execute on passengers if entity @s[tag=aj.carapacer.bone.right2] run function animated_java:carapacer/variants/damaged/zzz/apply_to_bone_right2
execute on passengers if entity @s[tag=aj.carapacer.bone.left2] run function animated_java:carapacer/variants/damaged/zzz/apply_to_bone_left2
execute on passengers if entity @s[tag=aj.carapacer.bone.top_mouth2] run function animated_java:carapacer/variants/damaged/zzz/apply_to_bone_top_mouth2
execute on passengers if entity @s[tag=aj.carapacer.bone.top_mouth] run function animated_java:carapacer/variants/damaged/zzz/apply_to_bone_top_mouth
execute on passengers if entity @s[tag=aj.carapacer.bone.bottom_mouth] run function animated_java:carapacer/variants/damaged/zzz/apply_to_bone_bottom_mouth
execute on passengers if entity @s[tag=aj.carapacer.bone.main_head] run function animated_java:carapacer/variants/damaged/zzz/apply_to_bone_main_head
return 1