# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.weapons.animation.sword1.playing
tag @s remove aj.weapons.animation.sword2.playing
tag @s remove aj.weapons.animation.sword_running.playing
tag @s remove aj.weapons.animation.sword1far.playing
tag @s remove aj.weapons.animation.sword2far.playing
tag @s remove aj.weapons.animation.sword3far.playing
tag @s remove aj.weapons.animation.sword_running_far.playing
tag @s remove aj.weapons.animation.hoe1.playing
tag @s remove aj.weapons.animation.hoe2.playing
tag @s remove aj.weapons.animation.pickaxe1.playing
tag @s remove aj.weapons.animation.axe1.playing
tag @s remove aj.weapons.animation.axe2.playing
tag @s remove aj.weapons.animation.shovel1.playing
tag @s remove aj.weapons.animation.shovel2.playing
tag @s remove aj.weapons.animation.jump1.playing