# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.9914f,-0.1305f,0f,0.1875f,-0.1305f,0.9914f,0f,1.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.9914f,0.1305f,0f,-0.1875f,0.1305f,0.9914f,0f,1.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.9537f,0.3007f,1.7182f,0f,0.3007f,-0.9537f,0.2067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.4926f,0.132f,2.5009f,0f,-0.132f,0.4926f,0.4389f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9659f,-0.2588f,2.1387f,0f,-0.2588f,-0.9659f,0.5359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [-1.9829f,0.2366f,-0.1103f,0.038f,-0.1103f,0.0066f,1.9969f,1.7913f,0.2366f,1.9859f,0.0066f,1.1467f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,0.0193f,0f,0f,0f,1.7282f,0f,0f,0f,0.9603f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,0.0193f,0f,0f,0f,1.7282f,0f,0f,0f,0.9603f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.7373f,-0.6756f,0f,-0.4375f,-0.2855f,0.3116f,-0.9063f,2.0171f,0.6123f,-0.6682f,-0.4226f,0.3409f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.024f,0f,0f,0f,1.9807f,0f,0f,0f,1.0748f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-0.7891f,0.5965f,0.1465f,0.4375f,0.0207f,0.2642f,-0.9643f,2.0171f,-0.6139f,-0.7579f,-0.2208f,0.3409f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,1.4891f,0.399f,2.2702f,0f,0.399f,-1.4891f,0.1187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9537f,0.3007f,1.0625f,0f,0.3007f,-0.9537f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}