# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.999f,-0.0436f,0f,0.1875f,-0.0436f,0.999f,0f,1.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.999f,0.0436f,0f,-0.1875f,0.0436f,0.999f,0f,1.0625f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.9537f,0.3007f,1.7182f,0f,0.3007f,-0.9537f,0.2067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.4712f,-0.1952f,2.4851f,0f,0.1952f,0.4712f,0.6794f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9239f,0.3827f,2.1387f,0f,0.3827f,-0.9239f,0.5359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.9613f,0f,0f,0f,1.421f,0f,0f,0f,0.5555f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [-0.03f,1.6211f,1.1709f,-0.7727f,0.7007f,-1.0883f,1.5247f,1.3666f,1.873f,0.4331f,-0.5517f,0.5789f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.9613f,0f,0f,0f,1.421f,0f,0f,0f,0.5555f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.8585f,0.5126f,0.015f,-0.4375f,0.4756f,0.8069f,-0.3504f,2.0171f,-0.1917f,-0.2937f,-0.9365f,0.3409f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,1.2135f,0f,0f,0f,0.5636f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.999f,-0.0436f,2.0171f,0f,-0.0436f,-0.999f,0.3409f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,1.4766f,0.443f,2.2702f,0f,0.443f,-1.4766f,0.1187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9537f,0.3007f,1.0625f,0f,0.3007f,-0.9537f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}