# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.9917f,-0.1272f,-0.0167f,0.1875f,-0.1239f,0.9157f,0.3823f,1.0625f,-0.0334f,0.3812f,-0.9239f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.999f,0.043f,0.0076f,-0.1875f,0.0436f,0.9839f,0.1735f,1.0625f,0f,0.1736f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.9537f,0.3007f,1.7182f,0f,0.3007f,-0.9537f,0.2067f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.4712f,-0.1952f,2.4851f,0f,0.1952f,0.4712f,0.6794f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9239f,0.3827f,2.1387f,0f,0.3827f,-0.9239f,0.5359f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.6665f,0f,0f,0f,1.2291f,0f,0f,0f,0.3908f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [-1.9772f,0.0804f,0.2901f,-0.6499f,0.2662f,-0.4336f,1.9342f,1.2489f,0.1406f,1.9508f,0.4179f,0.5867f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.6665f,0f,0f,0f,1.2291f,0f,0f,0f,0.3908f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.9886f,0.1297f,-0.0764f,-0.4375f,0.1331f,0.9903f,-0.0409f,2.0171f,0.0703f,-0.0506f,-0.9962f,0.3409f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5316f,0f,0f,0f,1.2102f,0f,0f,0f,0.5668f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-0.9889f,0.0021f,0.1485f,0.4375f,-0.002f,0.9996f,-0.0271f,2.0171f,-0.1485f,-0.0271f,-0.9885f,0.3409f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,1.2742f,0.8679f,2.2702f,0f,0.8679f,-1.2742f,0.1187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9537f,0.3007f,1.0625f,0f,0.3007f,-0.9537f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}