# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$execute as $(uuid) positioned ^$(px) ^$(py) ^$(pz) rotated ~$(ry) ~$(rx) run tp @s ~ ~ ~ ~ ~