# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.carapacer.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'carapacer', 'function_path': 'animated_java:carapacer/animations/walk_small_new/play'}
tag @s add aj.carapacer.animation.walk_small_new.playing
scoreboard players set @s aj.walk_small_new.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:carapacer/animations/walk_small_new/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only