# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.enchanted_witch.root] run return 0
execute on passengers if entity @s[tag=aj.enchanted_witch.data] unless data entity @s {data:{rigHash: 'd131468f5902c2c6f680ba89cf9cce7bd37328f31e18e255e3bd3a70d01bdc88'}} on vehicle run function animated_java:enchanted_witch/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1