# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.enchanted_witch.root] run return 0
execute if entity @s[tag=aj.enchanted_witch.animation.idle.playing] run function animated_java:enchanted_witch/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.enchanted_witch.animation.t_pose.playing] run function animated_java:enchanted_witch/animations/t_pose/zzz/on_tick
execute if entity @s[tag=aj.enchanted_witch.animation.taze_attack.playing] run function animated_java:enchanted_witch/animations/taze_attack/zzz/on_tick
execute if entity @s[tag=aj.enchanted_witch.animation.walk.playing] run function animated_java:enchanted_witch/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.enchanted_witch.animation.teleport.playing] run function animated_java:enchanted_witch/animations/teleport/zzz/on_tick
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:enchanted_witch/root/on_tick/transform_floating_entities
execute on passengers run rotate @s ~ ~