# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '509cec60ba6b3f83adce879ca2aed4612de4a532017b1b601aafdc65a9222e14'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack