# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '3f8d9363da0ea077675f6b5d36afb85588efa6712f367c7460c5db82c03e519d'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack