# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: 'c7a3e92ff11c05df6528c1cd2becbf51db433430cd36e1269234e6b9c7859bd5'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack