# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.7986f,0.6018f,0.7366f,0f,0.6018f,-0.7986f,0.4137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.5077f,-0.0489f,1.3963f,0f,0.0489f,0.5077f,0.9003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9954f,0.0958f,1.023f,0f,0.0958f,-0.9954f,0.8644f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.6369f,0f,0f,0f,0.1762f,0f,0f,0f,0.6264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [-0.1977f,0.0224f,0.0207f,-0.6341f,0.0177f,-0.0267f,0.1974f,0.1798f,0.0248f,0.1969f,0.0244f,0.6456f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.6369f,0f,0f,0f,0.1762f,0f,0f,0f,0.6264f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.9883f,0.0933f,-0.1204f,-0.4375f,0.0883f,0.995f,0.047f,0.9736f,0.1241f,0.0358f,-0.9916f,0.64f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,0.1602f,0f,0f,0f,0.8239f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,1f,0.0044f,0.9736f,0f,0.0044f,-1f,0.64f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,0.9385f,1.2231f,1.2863f,0f,1.2231f,-0.9385f,0.515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.7986f,0.6018f,0.1875f,0f,0.6018f,-0.7986f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}