# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.8434f,0.5373f,0.7673f,0f,0.5373f,-0.8434f,0.3694f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.5023f,-0.0886f,1.4576f,0f,0.0886f,0.5023f,0.8613f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9848f,0.1736f,1.0883f,0f,0.1736f,-0.9848f,0.7962f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1.2398f,0f,0f,0f,0.844f,0f,0f,0f,0.6003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [-0.3991f,0.2546f,1.9432f,-1.1552f,0.6462f,-1.8551f,0.3758f,0.6818f,1.8502f,0.7028f,0.288f,0.6752f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-1.2398f,0f,0f,0f,0.844f,0f,0f,0f,0.6003f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.1996f,0.9568f,-0.2115f,-0.4375f,0.3231f,0.268f,0.9076f,1.0213f,0.9251f,0.1128f,-0.3626f,0.5763f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,0.2014f,0f,0f,0f,0.7282f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.999f,0.0436f,1.0213f,0f,0.0436f,-0.999f,0.5763f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,0.9385f,1.2231f,1.3234f,0f,1.2231f,-0.9385f,0.4272f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.8434f,0.5373f,0.1875f,0f,0.5373f,-0.8434f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}