# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.8039f,0.5948f,0.7402f,0f,0.5948f,-0.8039f,0.4089f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.5072f,-0.0533f,1.4035f,0f,0.0533f,0.5072f,0.8963f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9945f,0.1045f,1.0306f,0f,0.1045f,-0.9945f,0.8571f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.7161f,0f,0f,0f,0.2061f,0f,0f,0f,0.6071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [-0.3815f,0.0838f,0.0861f,-0.7056f,0.0695f,-0.0797f,0.3858f,0.2107f,0.0979f,0.3829f,0.0615f,0.6449f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.7161f,0f,0f,0f,0.2061f,0f,0f,0f,0.6071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.9538f,0.1962f,-0.2274f,-0.4375f,0.1739f,0.9781f,0.1145f,0.9791f,0.2449f,0.0697f,-0.967f,0.6331f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,0.165f,0f,0f,0f,0.8135f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,1f,0.0087f,0.9791f,0f,0.0087f,-1f,0.6331f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,0.9385f,1.2231f,1.2908f,0f,1.2231f,-0.9385f,0.5054f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.8039f,0.5948f,0.1875f,0f,0.5948f,-0.8039f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}