# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.809f,0.5878f,0.7437f,0f,0.5878f,-0.809f,0.4041f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.5067f,-0.0577f,1.4106f,0f,0.0577f,0.5067f,0.8921f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9936f,0.1132f,1.038f,0f,0.1132f,-0.9936f,0.8497f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.7984f,0f,0f,0f,0.2469f,0f,0f,0f,0.59f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [-0.5388f,0.1729f,0.1994f,-0.7759f,0.1513f,-0.1691f,0.5554f,0.2484f,0.2163f,0.5491f,0.1083f,0.6448f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.7984f,0f,0f,0f,0.2469f,0f,0f,0f,0.59f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.898f,0.306f,-0.316f,-0.4375f,0.2522f,0.9468f,0.2001f,0.9846f,0.3604f,0.1f,-0.9274f,0.6262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,0.1697f,0f,0f,0f,0.803f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9999f,0.0131f,0.9846f,0f,0.0131f,-0.9999f,0.6262f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,0.9385f,1.2231f,1.2952f,0f,1.2231f,-0.9385f,0.4957f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.809f,0.5878f,0.1875f,0f,0.5878f,-0.809f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}