# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.8141f,0.5807f,0.7472f,0f,0.5807f,-0.8141f,0.3992f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.5062f,-0.0622f,1.4176f,0f,0.0622f,0.5062f,0.8879f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9925f,0.1219f,1.0454f,0f,0.1219f,-0.9925f,0.8422f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.8813f,0f,0f,0f,0.2994f,0f,0f,0f,0.5761f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [-0.6587f,0.2753f,0.361f,-0.8442f,0.2551f,-0.3018f,0.6956f,0.2929f,0.3755f,0.6879f,0.1607f,0.6457f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.8813f,0f,0f,0f,0.2994f,0f,0f,0f,0.5761f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.8234f,0.4195f,-0.3821f,-0.4375f,0.3189f,0.8991f,0.3f,0.99f,0.4694f,0.1252f,-0.8741f,0.6192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,0.1744f,0f,0f,0f,0.7925f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9998f,0.0175f,0.99f,0f,0.0175f,-0.9998f,0.6192f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,0.9385f,1.2231f,1.2994f,0f,1.2231f,-0.9385f,0.4861f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.8141f,0.5807f,0.1875f,0f,0.5807f,-0.8141f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}