# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.829f,0.5592f,0.7575f,0f,0.5592f,-0.829f,0.3844f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.5044f,-0.0754f,1.438f,0f,0.0754f,0.5044f,0.8749f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.989f,0.1478f,1.0671f,0f,0.1478f,-0.989f,0.8195f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1.1065f,0f,0f,0f,0.5296f,0f,0f,0f,0.5626f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [-0.7311f,0.4929f,1.0874f,-1.0263f,0.582f,-0.9662f,0.8293f,0.4649f,1.0424f,0.8852f,0.2997f,0.6549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-1.1065f,0f,0f,0f,0.5296f,0f,0f,0f,0.5626f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.5222f,0.7431f,-0.4184f,-0.4375f,0.4157f,0.6503f,0.6359f,1.006f,0.7446f,0.1581f,-0.6485f,0.598f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,0.1881f,0f,0f,0f,0.7606f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9995f,0.0305f,1.006f,0f,0.0305f,-0.9995f,0.598f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,0.9385f,1.2231f,1.3118f,0f,1.2231f,-0.9385f,0.4568f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.829f,0.5592f,0.1875f,0f,0.5592f,-0.829f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}