# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.8387f,0.5446f,0.7641f,0f,0.5446f,-0.8387f,0.3744f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.503f,-0.0842f,1.4512f,0f,0.0842f,0.503f,0.8659f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9863f,0.165f,1.0813f,0f,0.165f,-0.9863f,0.804f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-1.2094f,0f,0f,0f,0.7334f,0f,0f,0f,0.5817f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [-0.5429f,0.4037f,1.668f,-1.1194f,0.6757f,-1.5579f,0.597f,0.6061f,1.5776f,0.8062f,0.3184f,0.6672f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-1.2094f,0f,0f,0f,0.7334f,0f,0f,0f,0.5817f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.3016f,0.9036f,-0.3042f,-0.4375f,0.3754f,0.4058f,0.8333f,1.0163f,0.8764f,0.1372f,-0.4616f,0.5836f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,0.197f,0f,0f,0f,0.739f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9992f,0.0393f,1.0163f,0f,0.0393f,-0.9992f,0.5836f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,0.9385f,1.2231f,1.3196f,0f,1.2231f,-0.9385f,0.4371f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.8387f,0.5446f,0.1875f,0f,0.5446f,-0.8387f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}