# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.sword2far.frame matches 16.. run scoreboard players set @s aj.sword2far.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.sword2far.frame
execute at @s run function animated_java:weapons/animations/sword2far/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.sword2far.frame 1