# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.9914f,-0.1305f,0f,0.1875f,-0.0338f,0.2566f,0.9659f,0.1875f,-0.1261f,0.9577f,-0.2588f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.9914f,0.1305f,0f,-0.1875f,0.0338f,0.2566f,0.9659f,0.1875f,0.1261f,0.9577f,-0.2588f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-1f,0f,0f,0f,0f,0.2588f,0.9659f,-0.0875f,0f,0.9659f,-0.2588f,-1.0263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.7934f,0.6088f,0.7329f,0f,0.6088f,-0.7934f,0.4185f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.5081f,-0.0444f,1.389f,0f,0.0444f,0.5081f,0.9043f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,1.0155f,0f,0.0872f,-0.9962f,0.8717f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,0.1554f,0f,0f,0f,0.6468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,0.1554f,0f,0f,0f,0.6468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,0.1554f,0f,0f,0f,0.6468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,-0.4375f,0f,1f,0f,0.9679f,0f,0f,-1f,0.6468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,0.1554f,0f,0f,0f,0.8343f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,1f,0f,0.9679f,0f,0f,-1f,0.6468f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,0.9385f,1.2231f,1.2818f,0f,1.2231f,-0.9385f,0.5246f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.7934f,0.6088f,0.1875f,0f,0.6088f,-0.7934f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}