# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.second_officer.root] run return 0
execute if entity @s[tag=aj.second_officer.animation.idle.playing] run function animated_java:second_officer/animations/idle/zzz/on_tick
execute if entity @s[tag=aj.second_officer.animation.walk.playing] run function animated_java:second_officer/animations/walk/zzz/on_tick
execute if entity @s[tag=aj.second_officer.animation.jump.playing] run function animated_java:second_officer/animations/jump/zzz/on_tick
execute if entity @s[tag=aj.second_officer.animation.teleport_dark_hand.playing] run function animated_java:second_officer/animations/teleport_dark_hand/zzz/on_tick
execute if entity @s[tag=aj.second_officer.animation.left_right.playing] run function animated_java:second_officer/animations/left_right/zzz/on_tick
execute if entity @s[tag=aj.second_officer.animation.stab_far.playing] run function animated_java:second_officer/animations/stab_far/zzz/on_tick
execute if entity @s[tag=aj.second_officer.animation.spin_slash.playing] run function animated_java:second_officer/animations/spin_slash/zzz/on_tick
execute if entity @s[tag=aj.second_officer.animation.up_down_long.playing] run function animated_java:second_officer/animations/up_down_long/zzz/on_tick
execute on passengers run rotate @s ~ ~