# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.9914f,-0.1305f,0f,0.1875f,0.0338f,-0.2566f,0.9659f,0.1875f,-0.1261f,0.9577f,0.2588f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.9914f,0.1305f,0f,-0.1875f,-0.0338f,-0.2566f,0.9659f,0.1875f,0.1261f,0.9577f,0.2588f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-1f,0f,0f,0f,0f,-0.2588f,0.9659f,0.4625f,0f,0.9659f,0.2588f,-1.0263f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,-0.4226f,0.9063f,-0.1031f,0f,0.9063f,0.4226f,0.6231f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.0666f,-0.5056f,-0.4353f,0f,0.5056f,0.0666f,1.3688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.1305f,0.9914f,-0.4843f,0f,0.9914f,-0.1305f,0.997f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-0.9958f,0f,0f,0f,0.5268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-0.9958f,0f,0f,0f,0.5268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-0.9958f,0f,0f,0f,0.5268f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.887f,0.4617f,-0.2751f,0f,0.4617f,-0.887f,0.9019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,-0.9184f,0f,0f,0f,0.3715f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.6088f,0.7934f,-0.2751f,0f,0.7934f,-0.6088f,0.9019f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,-0.991f,1.181f,-0.0878f,0f,1.181f,0.991f,1.1819f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,-0.4226f,0.9063f,0.1875f,0f,0.9063f,0.4226f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}