# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.9948f,-0.1021f,-0.0051f,0.1874f,0.0302f,-0.3411f,0.9395f,0.0211f,-0.0976f,0.9345f,0.3424f,-0.0047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.9873f,0.1589f,-0.0051f,-0.1874f,-0.0591f,-0.3373f,0.9395f,0.0156f,0.1476f,0.9279f,0.3424f,0.0047f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-0.9996f,0.0286f,-0.0051f,-0.0304f,-0.0146f,-0.3422f,0.9395f,0.3819f,0.0252f,0.9392f,0.3424f,-0.9979f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,-0.5f,0.866f,-0.3254f,0f,0.866f,0.5f,0.5954f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.0222f,-0.5095f,-0.7214f,0f,0.5095f,0.0222f,1.3093f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.0436f,0.999f,-0.7378f,0f,0.999f,-0.0436f,0.9347f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-1.269f,0f,0f,0f,0.5407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-1.269f,0f,0f,0f,0.5407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-1.269f,0f,0f,0f,0.5407f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.9205f,0.3907f,-0.5211f,0f,0.3907f,-0.9205f,0.8582f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,-1.2243f,0f,0f,0f,0.4101f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.7009f,0.7133f,-0.5211f,0f,0.7133f,-0.7009f,0.8582f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,-1.0901f,1.0901f,-0.3589f,0f,1.0901f,1.0901f,1.1534f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,-0.5f,0.866f,0.0183f,0f,0.866f,0.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}