# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.9973f,-0.0729f,-0.0051f,0.1872f,0.0262f,-0.4223f,0.9061f,-0.1454f,-0.0682f,0.9035f,0.4231f,-0.0094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.9822f,0.1877f,-0.0051f,-0.1872f,-0.084f,-0.4147f,0.9061f,-0.1563f,0.168f,0.8904f,0.4231f,0.0094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-0.9983f,0.0579f,-0.0051f,-0.0616f,-0.0291f,-0.4221f,0.9061f,0.2977f,0.0503f,0.9047f,0.4231f,-0.9612f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,-0.5736f,0.8192f,-0.5452f,0f,0.8192f,0.5736f,0.5632f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,-0.0222f,-0.5095f,-1.0019f,0f,0.5095f,-0.0222f,1.2398f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,-0.0436f,0.999f,-0.9855f,0f,0.999f,0.0436f,0.8652f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-1.5335f,0f,0f,0f,0.5501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-1.5335f,0f,0f,0f,0.5501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-1.5335f,0f,0f,0f,0.5501f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.9483f,0.3173f,-0.763f,0f,0.3173f,-0.9483f,0.8079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,-1.5156f,0f,0f,0f,0.4489f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.7826f,0.6225f,-0.763f,0f,0.6225f,-0.7826f,0.8079f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,-1.181f,0.991f,-0.6272f,0f,0.991f,1.181f,1.1161f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,-0.5736f,0.8192f,-0.1508f,0f,0.8192f,0.5736f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}