# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.999f,-0.0436f,0f,0.1868f,0.0218f,-0.4995f,0.866f,-0.3118f,-0.0378f,0.8652f,0.5f,-0.0142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.9763f,0.2164f,0f,-0.1868f,-0.1082f,-0.4881f,0.866f,-0.3282f,0.1874f,0.8455f,0.5f,0.0142f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-0.9962f,0.0872f,0f,-0.0926f,-0.0436f,-0.4981f,0.866f,0.2092f,0.0755f,0.8627f,0.5f,-0.9167f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,-0.6428f,0.766f,-0.7619f,0f,0.766f,0.6428f,0.5267f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,-0.0666f,-0.5056f,-1.2759f,0f,0.5056f,-0.0666f,1.1609f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,-0.1305f,0.9914f,-1.2269f,0f,0.9914f,0.1305f,0.7892f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-1.7886f,0f,0f,0f,0.5549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-1.7886f,0f,0f,0f,0.5549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-1.7886f,0f,0f,0f,0.5549f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.9703f,0.2419f,-1.0002f,0f,0.2419f,-0.9703f,0.7515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,-1.791f,0f,0f,0f,0.4868f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.8526f,0.5225f,-1.0002f,0f,0.5225f,-0.8526f,0.7515f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,-1.2629f,0.8843f,-0.8918f,0f,0.8843f,1.2629f,1.0704f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,-0.6428f,0.766f,-0.32f,0f,0.766f,0.6428f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}