# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.9959f,-0.0899f,0.0111f,0.1873f,0.0607f,-0.5711f,0.8186f,-0.4533f,-0.0672f,0.8159f,0.5742f,-0.0075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.9852f,0.171f,0.0111f,-0.1873f,-0.0892f,-0.5674f,0.8186f,-0.4587f,0.1463f,0.8055f,0.5742f,0.0075f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-0.9991f,0.0409f,0.0111f,-0.0435f,-0.0144f,-0.5741f,0.8186f,0.154f,0.0399f,0.8177f,0.5742f,-0.8688f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,-0.7071f,0.7071f,-0.9422f,0f,0.7071f,0.7071f,0.4861f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,-0.1104f,-0.4979f,-1.5095f,0f,0.4979f,-0.1104f,1.0732f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,-0.2164f,0.9763f,-1.4283f,0f,0.9763f,0.2164f,0.7071f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.0005f,0f,0f,0f,0.5552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.0005f,0f,0f,0f,0.5552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.0005f,0f,0f,0f,0.5552f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.9863f,0.165f,-1.1992f,0f,0.165f,-0.9863f,0.6893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,-2.0163f,0f,0f,0f,0.523f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.91f,0.4147f,-1.1992f,0f,0.4147f,-0.91f,0.6893f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,-1.3351f,0.7708f,-1.119f,0f,0.7708f,1.3351f,1.0165f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,-0.7071f,0.7071f,-0.456f,0f,0.7071f,0.7071f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}