# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.9905f,-0.1368f,0.0141f,0.1875f,0.0988f,-0.6361f,0.7653f,-0.5949f,-0.0957f,0.7594f,0.6436f,-0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.9922f,0.1242f,0.0141f,-0.1875f,-0.0692f,-0.64f,0.7653f,-0.5893f,0.1041f,0.7583f,0.6436f,0.0008f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-0.9999f,-0.0064f,0.0141f,0.0068f,0.0149f,-0.6435f,0.7653f,0.0917f,0.0042f,0.7654f,0.6436f,-0.8132f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,-0.766f,0.6428f,-1.1187f,0f,0.6428f,0.766f,0.4419f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,-0.1534f,-0.4864f,-1.735f,0f,0.4864f,-0.1534f,0.9773f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,-0.3007f,0.9537f,-1.6223f,0f,0.9537f,0.3007f,0.6197f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.2019f,0f,0f,0f,0.5511f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.2019f,0f,0f,0f,0.5511f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.2019f,0f,0f,0f,0.5511f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.9962f,0.0872f,-1.3925f,0f,0.0872f,-0.9962f,0.6219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,-2.2238f,0f,0f,0f,0.5564f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9537f,0.3007f,-1.3925f,0f,0.3007f,-0.9537f,0.6219f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,-1.3972f,0.6515f,-1.3411f,0f,0.6515f,1.3972f,0.9548f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,-0.766f,0.6428f,-0.5921f,0f,0.6428f,0.766f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}