# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.983f,-0.1834f,0.009f,0.1872f,0.136f,-0.6941f,0.7069f,-0.7364f,-0.1234f,0.6961f,0.7073f,0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.997f,0.0773f,0.009f,-0.1872f,-0.0483f,-0.7057f,0.7069f,-0.7198f,0.061f,0.7043f,0.7073f,-0.0059f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-0.9985f,-0.0535f,0.009f,0.0569f,0.0442f,-0.7059f,0.7069f,0.0219f,-0.0315f,0.7063f,0.7073f,-0.7504f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,-0.8192f,0.5736f,-1.2913f,0f,0.5736f,0.8192f,0.3943f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,-0.1952f,-0.4712f,-1.9519f,0f,0.4712f,-0.1952f,0.874f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,-0.3827f,0.9239f,-1.8084f,0f,0.9239f,0.3827f,0.5275f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.3921f,0f,0f,0f,0.5427f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.3921f,0f,0f,0f,0.5427f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.3921f,0f,0f,0f,0.5427f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,-0.4375f,0f,1f,0.0087f,-1.5797f,0f,0.0087f,-1f,0.5498f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,-2.4127f,0f,0f,0f,0.5861f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9833f,0.1822f,-1.5797f,0f,0.1822f,-0.9833f,0.5498f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,-1.4487f,0.5273f,-1.5575f,0f,0.5273f,1.4487f,0.8859f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,-0.8192f,0.5736f,-0.7281f,0f,0.5736f,0.8192f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}