# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.9875f,-0.1573f,0.0022f,0.1874f,0.1219f,-0.7564f,0.6426f,-0.8682f,-0.0995f,0.6349f,0.7662f,0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.9946f,0.1037f,0.0022f,-0.1874f,-0.078f,-0.7622f,0.6426f,-0.8599f,0.0683f,0.639f,0.7662f,-0.0029f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-0.9996f,-0.0271f,0.0022f,0.0287f,0.0221f,-0.7659f,0.6426f,-0.0503f,-0.0157f,0.6424f,0.7662f,-0.6826f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,-0.866f,0.5f,-1.4595f,0f,0.5f,0.866f,0.3437f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,-0.2355f,-0.4524f,-2.1594f,0f,0.4524f,-0.2355f,0.764f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,-0.4617f,0.887f,-1.9862f,0f,0.887f,0.4617f,0.4314f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.5708f,0f,0f,0f,0.5302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.5708f,0f,0f,0f,0.5302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.5708f,0f,0f,0f,0.5302f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.9976f,-0.0698f,-1.7603f,0f,-0.0698f,-0.9976f,0.4735f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,-2.5827f,0f,0f,0f,0.6111f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9981f,0.061f,-1.7603f,0f,0.061f,-0.9981f,0.4735f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,-1.4891f,0.399f,-1.7675f,0f,0.399f,1.4891f,0.8103f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,-0.866f,0.5f,-0.8641f,0f,0.5f,0.866f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}