# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.9914f,-0.1305f,0f,0.1875f,0.1069f,-0.8121f,0.5736f,-1f,-0.0749f,0.5687f,0.8192f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.9914f,0.1305f,0f,-0.1875f,-0.1069f,-0.8121f,0.5736f,-1f,0.0749f,0.5687f,0.8192f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-1f,0f,0f,0f,0f,-0.8192f,0.5736f,-0.1297f,0f,0.5736f,0.8192f,-0.6094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,-0.9063f,0.4226f,-1.6231f,0f,0.4226f,0.9063f,0.2906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,-0.274f,-0.4301f,-2.357f,0f,0.4301f,-0.274f,0.6482f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,-0.5373f,0.8434f,-2.1555f,0f,0.8434f,0.5373f,0.3319f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.7377f,0f,0f,0f,0.5137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.7377f,0f,0f,0f,0.5137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-2.7377f,0f,0f,0f,0.5137f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.989f,-0.1478f,-1.9341f,0f,-0.1478f,-0.989f,0.3936f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,-2.7336f,0f,0f,0f,0.6303f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.9981f,-0.061f,-1.9341f,0f,-0.061f,-0.9981f,0.3936f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,-1.5182f,0.2677f,-1.9706f,0f,0.2677f,1.5182f,0.7284f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,-0.9063f,0.4226f,-1f,0f,0.4226f,0.9063f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}