# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.9914f,-0.1305f,0f,0.1875f,0.0227f,-0.1722f,0.9848f,-1.4687f,-0.1285f,0.9764f,0.1736f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.9914f,0.1305f,0f,-0.1875f,-0.0227f,-0.1722f,0.9848f,-1.4687f,0.1285f,0.9764f,0.1736f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-1f,0f,0f,0f,0f,-0.1736f,0.9848f,-1.2842f,0f,0.9848f,0.1736f,-1.0464f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.0436f,0.999f,-1.4388f,0f,0.999f,-0.0436f,0.6868f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.2925f,-0.4178f,-1.3892f,0f,0.4178f,0.2925f,1.5017f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.5736f,0.8192f,-1.6043f,0f,0.8192f,-0.5736f,1.1945f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-1.5263f,0f,0f,0f,1.8236f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-1.5263f,0f,0f,0f,1.8236f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-1.5263f,0f,0f,0f,1.8236f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,-0.4375f,0f,0.0785f,-0.9969f,-1.4626f,0f,-0.9969f,-0.0785f,1.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,-1.3755f,0f,0f,0f,1.8429f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,0.1219f,-0.9925f,-1.4626f,0f,-0.9925f,-0.1219f,1.0136f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,-0.3337f,1.5051f,-1.1672f,0f,1.5051f,0.3337f,1.1755f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.0436f,0.999f,-1.4687f,0f,0.999f,-0.0436f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}