# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.9914f,-0.1305f,0f,0.1875f,-0.0749f,0.5687f,0.8192f,-1.9375f,-0.1069f,0.8121f,-0.5736f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.9914f,0.1305f,0f,-0.1875f,0.0749f,0.5687f,0.8192f,-1.9375f,0.1069f,0.8121f,-0.5736f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-1f,0f,0f,0f,0f,0.5736f,0.8192f,-2.5469f,0f,0.8192f,-0.5736f,-0.8703f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.9397f,0.342f,-1.2915f,0f,0.342f,-0.9397f,0.2351f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.4979f,0.1104f,-0.5196f,0f,-0.1104f,0.4979f,0.5012f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9763f,-0.2164f,-0.8857f,0f,-0.2164f,-0.9763f,0.5823f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-0.2238f,0f,0f,0f,0.6265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-0.2238f,0f,0f,0f,0.6265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.5625f,0f,0f,0f,-0.2238f,0f,0f,0f,0.6265f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-1f,0f,0f,-0.4375f,0f,-0.9537f,-0.3007f,-0.9987f,0f,-0.3007f,0.9537f,0.3822f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.5625f,0f,0f,0f,-0.1674f,0f,0f,0f,0.4477f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-1f,0f,0f,0.4375f,0f,-0.9537f,-0.3007f,-0.9987f,0f,-0.3007f,0.9537f,0.3822f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,1.2629f,0.8843f,-0.7361f,0f,0.8843f,-1.2629f,0.1712f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9397f,0.342f,-1.9375f,0f,0.342f,-0.9397f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}