# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:carapacer/animations/idle_big_new/zzz/apply_frame {frame: 50}
scoreboard players add @s aj.idle_big_new.frame 1