# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:enchanted_witch/animations/pause_all
tag @s add aj.enchanted_witch.animation.t_pose.playing
scoreboard players set @s aj.t_pose.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:enchanted_witch/animations/t_pose/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only