# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data remove storage animated_java:temp args
$execute store result storage animated_java:temp args.frame int 1 run scoreboard players set @s aj.t_pose.frame $(frame)
execute at @s run function animated_java:enchanted_witch/animations/t_pose/zzz/set_frame with storage animated_java:temp args