# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3125f,0f,0f,-1f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,-0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left2) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_mouth2) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,-0.5386f,0f,0.0872f,-0.9962f,0.7587f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_mouth) {transformation: [-1.0833f,0f,0f,0f,0f,1.0792f,0.0944f,-0.5386f,0f,0.0944f,-1.0792f,0.7587f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom_mouth) {transformation: [-1f,0f,0f,0f,0f,0.9763f,0.2164f,-0.2786f,0f,0.2164f,-0.9763f,0.656f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_main_head) {transformation: [-1f,0f,0f,0f,0f,0.9962f,0.0872f,-0.2919f,0f,0.0872f,-0.9962f,0.0902f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}