# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute on passengers if entity @s[tag=aj.global.data] run function animated_java:enchanted_witch/remove/this/as_data
execute on passengers if entity @s[tag=aj.global.data] unless data entity @s {data:{rig_hash: '08a2e380b22220e5257fdc06a160cdbf5189febb19702bbe82cb48971ca31c49'}} on vehicle run function animated_java:global/remove/outdated_rig
function animated_java:global/remove/entity_stack