# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_legs) {transformation: [-1f,0f,0f,0f,0f,0.9848f,0.1736f,1.25f,0f,0.1736f,-0.9848f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_backbling) {transformation: [0f,-1f,0f,0f,-1f,0f,0f,2.6875f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.5f,0.866f,0f,-0.5f,0.6871f,0.3967f,-0.6088f,2.375f,-0.5272f,-0.3044f,-0.7934f,0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-0.6428f,-0.766f,0f,0.5f,-0.766f,0.6428f,0f,2.375f,0f,0f,-1f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left2) {transformation: [-0.6428f,-0.7631f,-0.0668f,0.5f,-0.766f,0.6403f,0.056f,2.5f,0f,0.0872f,-0.9962f,-0.2187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [-0.6428f,0.7631f,0.0668f,-0.5f,0.766f,0.6403f,0.056f,2.5f,0f,0.0872f,-0.9962f,-0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9848f,-0.1736f,2.625f,0f,-0.1736f,-0.9848f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_spinny_part) {transformation: [1f,0f,0f,-1.4687f,0f,0.9763f,-0.2164f,2.8202f,0f,0.2164f,0.9763f,0.6568f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_staff) {transformation: [0f,0f,1.7292f,-1.4687f,0.3743f,1.6882f,0f,0.5625f,-1.6882f,0.3743f,0f,0.1562f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{"camera":{"px":-5.920553680217821e-17,"py":2.751668551188362,"pz":0.48344989627539486,"ry":0,"rx":-10.000000000000002}},"locators":{}}