# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_legs) {transformation: [-1f,0f,0f,0f,0f,1f,0f,1.25f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.1736f,0.9848f,0f,-0.5f,0.7813f,0.1378f,-0.6088f,2.375f,-0.5995f,-0.1057f,-0.7934f,0.0312f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-0.342f,-0.9397f,0f,0.5f,-0.9397f,0.342f,0f,2.375f,0f,0f,-1f,0.0313f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left2) {transformation: [-0.343f,-0.937f,-0.0668f,0.5f,-0.9389f,0.3397f,0.056f,2.5f,-0.0298f,0.0819f,-0.9962f,-0.2187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [-0.343f,0.937f,0.0668f,-0.5f,0.9389f,0.3397f,0.056f,2.5f,0.0298f,0.0819f,-0.9962f,-0.2188f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,2.625f,0f,0f,-1f,0.125f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_spinny_part) {transformation: [0f,1f,0f,1.0312f,-0.8988f,0f,-0.4384f,2f,-0.4384f,0f,0.8988f,0.7813f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_staff) {transformation: [0f,1.7292f,0f,-1.2812f,0f,0f,-1.7292f,2f,-1.7292f,0f,0f,0.7812f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{"camera":{"px":-6.123233995736766e-17,"py":2.6875,"pz":0.5,"ry":0,"rx":0}},"locators":{}}