# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_legs) {transformation: [-0.5f,0f,0f,0f,0f,0.5f,0f,1.4531f,0f,0f,-0.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_backbling) {transformation: [0f,0.5f,0f,0f,0.5f,0f,0f,2.1719f,0f,0f,-0.5f,-0.2187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-0.5f,0f,0f,0f,0f,0.5f,0f,1.8906f,0f,0f,-0.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-0.5f,0f,0f,0f,0f,0.5f,0f,1.4531f,0f,0f,-0.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.1698f,0.4703f,-0.0001f,-0.25f,0.3764f,0.1359f,-0.2998f,2.0156f,-0.2819f,-0.1019f,-0.4001f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-0.25f,-0.433f,0f,0.25f,-0.433f,0.25f,0f,2.0156f,0f,0f,-0.5f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left2) {transformation: [-0.2502f,-0.4316f,-0.0329f,0.25f,-0.4328f,0.2488f,0.0276f,2.0781f,-0.0075f,0.0423f,-0.4982f,-0.1094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [-0.2502f,0.4316f,0.0329f,-0.25f,0.4328f,0.2488f,0.0276f,2.0781f,0.0075f,0.0423f,-0.4982f,-0.1094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.5f,0f,0f,0f,0f,0.5f,0f,2.1406f,0f,0f,-0.5f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_spinny_part) {transformation: [0f,0.5f,0f,0.5156f,-0.4993f,0f,0.0262f,1.8281f,0.0262f,0f,0.4993f,0.3906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_staff) {transformation: [0f,0.8646f,0f,-0.6406f,0.6114f,0f,0.6114f,1.8281f,0.6114f,0f,-0.6114f,0.3906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{"camera":{"px":3.061616997868383e-17,"py":2.171875,"pz":0.25,"ry":360,"rx":0}},"locators":{}}