# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_legs) {transformation: [-0.5f,0f,0f,0f,0f,0.4924f,0.0868f,1.4531f,0f,0.0868f,-0.4924f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_backbling) {transformation: [-0.5f,0f,0f,0f,0f,0.5f,0f,2.1719f,0f,0f,-0.5f,-0.2187f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top) {transformation: [-0.5f,0f,0f,0f,0f,0.5f,0f,1.8906f,0f,0f,-0.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-0.5f,0f,0f,0f,0f,0.5f,0f,1.4531f,0f,0f,-0.5f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.25f,0.433f,0f,-0.25f,0.3435f,0.1983f,-0.3044f,2.0156f,-0.2636f,-0.1522f,-0.3967f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-0.3214f,-0.383f,0f,0.25f,-0.383f,0.3214f,0f,2.0156f,0f,0f,-0.5f,0.0156f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left2) {transformation: [-0.3214f,-0.3816f,-0.0334f,0.25f,-0.383f,0.3202f,0.028f,2.0781f,0f,0.0436f,-0.4981f,-0.1094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right2) {transformation: [-0.3214f,0.3816f,0.0334f,-0.25f,0.383f,0.3202f,0.028f,2.0781f,0f,0.0436f,-0.4981f,-0.1094f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-0.5f,0f,0f,0f,0f,0.4924f,-0.0868f,2.1406f,0f,-0.0868f,-0.4924f,0.0625f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_spinny_part) {transformation: [0f,0.5f,0f,0.5156f,-0.4806f,0f,0.1378f,1.8281f,0.1378f,0f,0.4806f,0.3906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_staff) {transformation: [0f,0.8646f,0f,-0.6406f,0.8646f,0f,0f,1.8281f,0f,0f,-0.8646f,0.3906f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
data modify entity @s data merge value {"cameras":{"camera":{"px":2.9602768401089105e-17,"py":2.203959275594181,"pz":0.24172494813769743,"ry":360,"rx":-10.000000000000002}},"locators":{}}