# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:carapacer/animations/walk_big_new/zzz/apply_frame {frame: 15}
scoreboard players add @s aj.walk_big_new.frame 1