# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[tag=aj.wormhole.root] run return 0
execute on passengers if entity @s[tag=aj.wormhole.data] unless data entity @s {data:{rigHash: '72f8c4663f07fee835b716ba73521edce5169f27cd4b024127b48f4fc010bf52'}} on vehicle run function animated_java:wormhole/root/zzz/check_rig_hash
scoreboard players set @s aj.is_rig_loaded 1