# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:second_officer/animations/pause_all
tag @s add aj.second_officer.animation.left_right.playing
scoreboard players set @s aj.left_right.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:second_officer/animations/left_right/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only