# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.sword_far3.frame matches 16.. run scoreboard players set @s aj.sword_far3.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.sword_far3.frame
execute at @s run function animated_java:weapons/animations/sword_far3/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.sword_far3.frame 1