# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.up_down_long.frame matches 46.. run scoreboard players set @s aj.up_down_long.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.up_down_long.frame
execute at @s run function animated_java:second_officer/animations/up_down_long/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.up_down_long.frame 1