# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data modify storage animated_java:temp args.uuid set from entity @s data.cameras.$(name).uuid
function animated_java:enchanted_witch/zzz/as_camera/execute_as_uuid with storage animated_java:temp args