# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:enchanted_witch/zzz/reset_floating_entities
execute on passengers if entity @s[tag=aj.enchanted_witch.node.legs] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.25f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.enchanted_witch.node.backbling] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.6875f,0f,0f,-1f,-0.4375f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.enchanted_witch.node.top] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.125f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.enchanted_witch.node.body] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,1.25f,0f,0f,-1f,0f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.enchanted_witch.node.right1] run data merge entity @s { transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,2.375f,0f,0f,-1f,0.0312f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.enchanted_witch.node.left1] run data merge entity @s { transformation: [-1f,0f,0f,0.5f,0f,1f,0f,2.375f,0f,0f,-1f,0.0313f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.enchanted_witch.node.left2] run data merge entity @s { transformation: [-1f,0f,0f,0.5f,0f,1f,0f,2.5f,0f,0f,-1f,-0.2187f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.enchanted_witch.node.right2] run data merge entity @s { transformation: [-1f,0f,0f,-0.5f,0f,1f,0f,2.5f,0f,0f,-1f,-0.2188f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.enchanted_witch.node.head] run data merge entity @s { transformation: [-1f,0f,0f,0f,0f,1f,0f,2.625f,0f,0f,-1f,0.125f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.enchanted_witch.node.spinny_part] run data merge entity @s { transformation: [-1f,0f,0f,-1.0312f,0f,1f,0f,2.25f,0f,0f,-1f,0.0312f,0f,0f,0f,1f], start_interpolation: 0 }
execute on passengers if entity @s[tag=aj.enchanted_witch.node.staff] run data merge entity @s { transformation: [-1.7292f,0f,0f,-1.0312f,0f,1.7292f,0f,-0.0625f,0f,0f,-1.7292f,0.0312f,0f,0f,0f,1f], start_interpolation: 0 }