# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:enchanted_witch rig_hash set value '08a2e380b22220e5257fdc06a160cdbf5189febb19702bbe82cb48971ca31c49'
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.t_pose.frame dummy
scoreboard objectives add aj.taze_attack.frame dummy
scoreboard objectives add aj.walk.frame dummy
scoreboard objectives add aj.teleport.frame dummy