# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.idle.frame dummy
scoreboard objectives add aj.t_pose.frame dummy
scoreboard objectives add aj.taze_attack.frame dummy
scoreboard objectives add aj.walk.frame dummy