# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.idle.frame
scoreboard objectives remove aj.t_pose.frame
scoreboard objectives remove aj.taze_attack.frame
scoreboard objectives remove aj.walk.frame
scoreboard objectives remove aj.teleport.frame
tellraw @a [{color:'gray',text:'\n '},{color:'#00aced',text:'ᴀɴɪᴍᴀᴛᴇᴅ ᴊᴀᴠᴀ'},{color:'dark_gray',italic:true,text:'\n (animated_java:enchanted_witch)'},'\n → ',{color:'green',text:'Successfully uninstalled '},{color:'yellow',text:'enchanted_witch'},{color:'green',text:'!'},{color:'gray',italic:true,text:'\n If you have exported multiple times, you may have to remove objectives from previous exports manually, as Animated Java only knows about the objectives from the most recent export.'},'\n']