# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute unless entity @s[type=minecraft:item_display,tag=aj.enchanted_witch.root] run return run function animated_java:global/errors/function_not_executed_as_root_entity {'export_namespace': 'enchanted_witch', 'function_path': 'animated_java:enchanted_witch/animations/pause_all'}
tag @s remove aj.enchanted_witch.animation.idle.playing
tag @s remove aj.enchanted_witch.animation.t_pose.playing
tag @s remove aj.enchanted_witch.animation.taze_attack.playing
tag @s remove aj.enchanted_witch.animation.walk.playing