# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
tag @s remove aj.enchanted_witch.animation.idle.playing
tag @s remove aj.enchanted_witch.animation.t_pose.playing
tag @s remove aj.enchanted_witch.animation.taze_attack.playing
tag @s remove aj.enchanted_witch.animation.walk.playing
tag @s remove aj.enchanted_witch.animation.teleport.playing