# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.teleport_dark_hand.frame matches 41.. run scoreboard players set @s aj.teleport_dark_hand.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.teleport_dark_hand.frame
execute at @s run function animated_java:second_officer/animations/teleport_dark_hand/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.teleport_dark_hand.frame 1