# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:second_officer/animations/pause_all
tag @s add aj.second_officer.animation.teleport_dark_hand.playing
scoreboard players set @s aj.teleport_dark_hand.frame 0
tag @s add aj.transforms_only
execute at @s run function animated_java:second_officer/animations/teleport_dark_hand/zzz/set_frame {frame: 0}
tag @s remove aj.transforms_only