# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
data modify storage animated_java:weapons rig_hash set value '3f8d9363da0ea077675f6b5d36afb85588efa6712f367c7460c5db82c03e519d'
scoreboard objectives add aj.sword1.frame dummy
scoreboard objectives add aj.sword2.frame dummy
scoreboard objectives add aj.hoe1.frame dummy
scoreboard objectives add aj.hoe2.frame dummy
scoreboard objectives add aj.pickaxe1.frame dummy
scoreboard objectives add aj.axe1.frame dummy
scoreboard objectives add aj.axe2.frame dummy
scoreboard objectives add aj.shovel1.frame dummy
scoreboard objectives add aj.shovel2.frame dummy
scoreboard objectives add aj.jump1.frame dummy