# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
summon minecraft:item_display ^0 ^2.6875 ^0.5 {Tags:["aj.enchanted_witch.bone.all.decendant","aj.enchanted_witch.bone.all.decendant.camera","aj.enchanted_witch.bone.all.tree","aj.enchanted_witch.bone.head.child","aj.enchanted_witch.bone.head.child.camera","aj.enchanted_witch.bone.head.decendant","aj.enchanted_witch.bone.head.decendant.camera","aj.enchanted_witch.bone.head.tree","aj.enchanted_witch.camera","aj.enchanted_witch.camera.camera","aj.enchanted_witch.entity","aj.enchanted_witch.node","aj.enchanted_witch.node.camera","aj.global.bone.all.decendant","aj.global.bone.all.decendant.camera","aj.global.bone.all.tree","aj.global.bone.head.child","aj.global.bone.head.child.camera","aj.global.bone.head.decendant","aj.global.bone.head.decendant.camera","aj.global.bone.head.tree","aj.global.camera","aj.global.entity","aj.global.node","aj.global.node.camera","aj.new"], teleport_duration: 2}
execute as @n[ type=minecraft:item_display, tag=aj.new, tag=aj.enchanted_witch.camera.camera, distance=..3 ] run function animated_java:enchanted_witch/zzz/summon/as_data_entity/as_camera/camera
data modify entity @s data.uuids.camera_camera set from storage aj:uuid main.out
data modify entity @s data.cameras.camera.uuid set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enchanted_witch.node.legs] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_legs set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enchanted_witch.node.backbling] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_backbling set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enchanted_witch.node.top] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enchanted_witch.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enchanted_witch.node.right1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enchanted_witch.node.left1] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left1 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enchanted_witch.node.left2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enchanted_witch.node.right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enchanted_witch.node.head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_head set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enchanted_witch.node.spinny_part] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_spinny_part set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.enchanted_witch.node.staff] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_staff set from storage aj:uuid main.out