# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.data_data set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.carapacer.node.body] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_body set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.carapacer.node.left] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.carapacer.node.right] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.carapacer.node.right2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_right2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.carapacer.node.left2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_left2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.carapacer.node.top_mouth2] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top_mouth2 set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.carapacer.node.top_mouth] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_top_mouth set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.carapacer.node.bottom_mouth] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_bottom_mouth set from storage aj:uuid main.out
execute on vehicle on passengers if entity @s[tag=aj.carapacer.node.main_head] run function animated_java:global/internal/gu/convert_uuid_array_to_string
data modify entity @s data.uuids.bone_main_head set from storage aj:uuid main.out