# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_left) {transformation: [-0.999f,-0.0433f,-0.0076f,0.1875f,-0.0438f,0.9953f,0.0868f,1.0625f,0.0038f,0.0871f,-0.9962f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right) {transformation: [-0.999f,0.0436f,-0.0019f,-0.1875f,0.0436f,0.9981f,-0.0436f,1.0625f,0f,-0.0436f,-0.999f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cloth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_upper) {transformation: [-1f,0f,0f,0f,0f,0.9763f,0.2164f,1.7337f,0f,0.2164f,-0.9763f,0.1488f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display4) {transformation: [0.51f,0f,0f,0f,0f,0.4622f,-0.2155f,2.5211f,0f,0.2155f,0.4622f,0.5986f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_head) {transformation: [-1f,0f,0f,0f,0f,0.9063f,0.4226f,2.1813f,0f,0.4226f,-0.9063f,0.4401f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display) {transformation: [-1.7453f,-0.1587f,0.9638f,-0.0911f,0.1092f,-1.9928f,-0.1303f,1.5061f,0.9706f,-0.0611f,1.7476f,0.9174f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display1) {transformation: [0f,0f,0f,-0.1064f,0f,0f,0f,1.697f,0f,0f,0f,0.8685f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display3) {transformation: [0f,0f,0f,-0.1064f,0f,0f,0f,1.697f,0f,0f,0f,0.8685f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_right1) {transformation: [-0.8434f,-0.5373f,0f,-0.4375f,-0.2481f,0.3894f,-0.887f,2.0444f,0.4766f,-0.7481f,-0.4617f,0.2011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(item_display_item_display2) {transformation: [0f,0f,0f,0.1064f,0f,0f,0f,1.8633f,0f,0f,0f,0.9551f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_left1) {transformation: [-0.8434f,0.5373f,0f,0.4375f,0.2481f,0.3894f,-0.887f,2.0444f,-0.4766f,-0.7481f,-0.4617f,0.2011f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_cape) {transformation: [-1.5417f,0f,0f,0f,0f,1.5285f,0.2012f,2.276f,0f,0.2012f,-1.5285f,0.0129f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,0.9763f,0.2164f,1.0625f,0f,0.2164f,-0.9763f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}