# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives add aj.transform__big_new.frame dummy
scoreboard objectives add aj.walk_small_new.frame dummy
scoreboard objectives add aj.walk_big_new.frame dummy
scoreboard objectives add aj.attack_new.frame dummy
scoreboard objectives add aj.idle_small_new.frame dummy
scoreboard objectives add aj.idle_big_new.frame dummy