# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
scoreboard objectives remove aj.transform__big_new.frame
scoreboard objectives remove aj.walk_small_new.frame
scoreboard objectives remove aj.walk_big_new.frame
scoreboard objectives remove aj.attack_new.frame
scoreboard objectives remove aj.idle_small_new.frame
scoreboard objectives remove aj.idle_big_new.frame
tellraw @a [[{"text":"\n[","color":"gray"},{"text":"AJ","color":"aqua"},"] ",[{"text":"(from ","color":"gray","italic":true},"carapacer",")"]," -> "],{"text":"Successfully removed known animation scoreboard objectives.","color":"red"},{"text":"\nIf you have exported multiple times you may have to manually remove some objectives from previous exports manually, as Animated Java can only remove the latest export's objectives.","color":"gray","italic":true},["\n"]]