# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
$data merge entity $(bone_body) {transformation: [-1f,0f,0f,0f,0f,1f,0f,0.3125f,0f,0f,-1f,0f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_mouth2) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.5625f,0f,0f,-1f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_top_mouth) {transformation: [-1.0833f,0f,0f,0f,0f,1.0833f,0f,-0.5625f,0f,0f,-1.0833f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_bottom_mouth) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.375f,0f,0f,-1f,0.875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}
$data merge entity $(bone_main_head) {transformation: [-1f,0f,0f,0f,0f,1f,0f,-0.375f,0f,0f,-1f,0.1875f,0f,0f,0f,1f],start_interpolation: 0,interpolation_duration: 1}