# This file was generated by Animated Java via MC-Build. It is not recommended to edit this file directly.
execute if score @s aj.stab_far.frame matches 61.. run scoreboard players set @s aj.stab_far.frame 1
data remove storage animated_java:temp args
execute store result storage animated_java:temp args.frame int 1 run scoreboard players get @s aj.stab_far.frame
execute at @s run function animated_java:second_officer/animations/stab_far/zzz/apply_frame with storage animated_java:temp args
scoreboard players add @s aj.stab_far.frame 1